"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _hero_section from './hero-section.bones.json'

registerBones({
  "hero-section": _hero_section,
})
