"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _hero_section from './hero-section.bones.json'

configureBoneyard({"animate":"pulse"})

registerBones({
  "hero-section": _hero_section,
})
